base_images:
  cluster-storage-operator-test:
    name: "4.20"
    namespace: ocp
    tag: cluster-storage-operator-test
build_root:
  from_repository: true
releases:
  initial:
    candidate:
      product: ocp
      stream: nightly
      version: "4.19"
  latest:
    integration:
      include_built_images: true
      name: "4.20"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn-upgrade-check-dev-symlinks
  cron: '@daily'
  steps:
    cluster_profile: aws-2
    workflow: openshift-upgrade-aws-storage-symlinks
zz_generated_metadata:
  branch: main
  org: openshift
  repo: cluster-storage-operator
  variant: 4.20-upgrade-from-stable-4.19
