base_images:
  cluster-storage-operator-test:
    name: "4.21"
    namespace: ocp
    tag: cluster-storage-operator-test
build_root:
  from_repository: true
releases:
  initial:
    candidate:
      product: ocp
      stream: nightly
      version: "4.20"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.21"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: periodic-e2e-aws-ovn-upgrade-check-dev-symlinks
  cron: '@daily'
  steps:
    cluster_profile: aws-2
    workflow: openshift-upgrade-aws-storage-symlinks
- as: periodic-e2e-gcp-ovn-upgrade-check-dev-symlinks
  cron: '@daily'
  steps:
    cluster_profile: gcp
    workflow: openshift-upgrade-gcp-storage-symlinks
- as: periodic-e2e-azure-ovn-upgrade-check-dev-symlinks
  cron: '@daily'
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-ovn
  timeout: 5h30m0s
zz_generated_metadata:
  branch: release-4.21
  org: openshift
  repo: cluster-storage-operator
  variant: periodics
